baseurl = "https://angelopili.it/"
title = "AngeloPili.it"
description = "Software Engineer Analyst di Monza Brianza, sviluppo applicativi in Php e Mysql su framework Laravel, Javascript ES6, React e Svelte."
theme = "smol"
languageCode = "en-us"

# Parameters
[params]
    subtitle = "Appunti di sviluppo"
    dateFmt = "02.01.2006"

# Header
[menu]
  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/angepili"
        weight = 1 

    [[menu.footer]]
        name = "Linkedin"
        url = "https://www.linkedin.com/in/angelopili/"
        weight = 2 

    [[menu.footer]]
        name = "Twitter"
        url = "https://twitter.com/ngpi71"
        weight = 3 




# baseURL = "https://angelopili.it"
# languageCode = "it-it"
# title = "Appunti di sviluppo | AngeloPili.it"
# theme = "stack"
# paginate = 10
# pygmentsStyle = "monokai"
# googleAnalytics = "UA-116693958-1"

# [sitemap]
#   changefreq = "weekly"
#   filename = "sitemap.xml"
#   priority = 0.8

# [params]
#   author = "AngeloPili.it"
#   authorName = "Angelo Pili"
#   description = "Software Engineer Analyst di Monza Brianza, sviluppo applicativi in Php e Mysql su framework Laravel, Javascript ES6, React e Svelte."
#   opengraphimage = "/uploads/cover.png"
#   titleheader = "AngeloPili.it"
#   subtitle = "Appunti di sviluppo"

# [menu]

#   [[menu.main]]
#     identifier = "chi-sono"
#     name = "chi-sono"
#     url = "/about/"
#     weight = 1

#   [[menu.main]]
#     identifier = "github"
#     name = "github"
#     url = "https://github.com/angepili"
#     weight = 2
#     type = "external"

#   [[menu.main]]
#     identifier = "linkedin"
#     name = "linkedin"
#     url = "https://www.linkedin.com/in/angelopili/"
#     weight = 3
#     type = "external"

#   [[menu.main]]
#     identifier = "twitter"
#     name = "twitter"
#     url = "https://twitter.com/ngpi71"
#     weight = 4
#     type = "external"

#   # [[menu.main]]
#   #   identifier = "facebook"
#   #   name = "facebook"
#   #   url = "https://www.facebook.com/appuntisviluppatore"
#   #   weight = 5
#   #   type = "external"

# [taxonomies]
#   category = "categories"
#   tag = "tags"
#   series = "series"