baseURL = "https://angelopili.it/"
languageCode = "en-us"
title = "AngeloPili.it"
description = "Software Engineer Analyst di Monza Brianza, sviluppo applicativi in Php e Mysql su framework Laravel, Javascript ES6, React e Svelte."
theme="archie"
copyright = "© AngeloPili.it"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
publishDir = "docs"
[params]
	mode="auto"
	useCDN=false
	subtitle = "Appunti di sviluppo"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/angepili"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ngpi71"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4




# baseURL = "https://angelopili.it"
# languageCode = "it-it"
# title = "Appunti di sviluppo | AngeloPili.it"
# theme = "stack"
# paginate = 10
# pygmentsStyle = "monokai"
# googleAnalytics = "UA-116693958-1"

# [sitemap]
#   changefreq = "weekly"
#   filename = "sitemap.xml"
#   priority = 0.8

# [params]
#   author = "AngeloPili.it"
#   authorName = "Angelo Pili"
#   description = "Software Engineer Analyst di Monza Brianza, sviluppo applicativi in Php e Mysql su framework Laravel, Javascript ES6, React e Svelte."
#   opengraphimage = "/uploads/cover.png"
#   titleheader = "AngeloPili.it"
#   subtitle = "Appunti di sviluppo"

# [menu]

#   [[menu.main]]
#     identifier = "chi-sono"
#     name = "chi-sono"
#     url = "/about/"
#     weight = 1

#   [[menu.main]]
#     identifier = "github"
#     name = "github"
#     url = "https://github.com/angepili"
#     weight = 2
#     type = "external"

#   [[menu.main]]
#     identifier = "linkedin"
#     name = "linkedin"
#     url = "https://www.linkedin.com/in/angelopili/"
#     weight = 3
#     type = "external"

#   [[menu.main]]
#     identifier = "twitter"
#     name = "twitter"
#     url = "https://twitter.com/ngpi71"
#     weight = 4
#     type = "external"

#   # [[menu.main]]
#   #   identifier = "facebook"
#   #   name = "facebook"
#   #   url = "https://www.facebook.com/appuntisviluppatore"
#   #   weight = 5
#   #   type = "external"

# [taxonomies]
#   category = "categories"
#   tag = "tags"
#   series = "series"