baseURL = "https://angepili.github.io/"
languageCode = "en-us"
title = "AngeloPili.it"
description = "Software Engineer Analyst di Monza Brianza, sviluppo applicativi in Php e Mysql su framework Laravel, Javascript ES6, React e Svelte."
theme="archie"
copyright = "© AngeloPili.it"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
publishDir = "docs"
googleAnalytics = "UA-116693958-1"

[params]
	mode="auto"
	useCDN=false
	subtitle = "Appunti di sviluppo"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/angepili"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ngpi71"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/pages"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4